
package edu.herzen.ParsecRemoverService.parsec3intergationservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IntegrationServiceSoap", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IntegrationServiceSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetVersion", action = "http://parsec.ru/Parsec3IntergationService/GetVersion")
    @WebResult(name = "GetVersionResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetVersion", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetVersion")
    @ResponseWrapper(localName = "GetVersionResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetVersionResponse")
    public String getVersion();

    /**
     * 
     * @param domain
     * @param userName
     * @param password
     * @return
     *     returns ru.parsec.parsec3intergationservice.SessionResult
     */
    @WebMethod(operationName = "OpenSession", action = "http://parsec.ru/Parsec3IntergationService/OpenSession")
    @WebResult(name = "OpenSessionResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "OpenSession", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.OpenSession")
    @ResponseWrapper(localName = "OpenSessionResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.OpenSessionResponse")
    public SessionResult openSession(
            @WebParam(name = "domain", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String domain,
            @WebParam(name = "userName", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String password);

    /**
     *
     * @param locale
     * @param domain
     * @param userName
     * @param password
     * @return
     *     returns ru.parsec.parsec3intergationservice.SessionResult
     */
    @WebMethod(operationName = "OpenSessionWithInLocale", action = "http://parsec.ru/Parsec3IntergationService/OpenSessionWithInLocale")
    @WebResult(name = "OpenSessionWithInLocaleResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "OpenSessionWithInLocale", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.OpenSessionWithInLocale")
    @ResponseWrapper(localName = "OpenSessionWithInLocaleResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.OpenSessionWithInLocaleResponse")
    public SessionResult openSessionWithInLocale(
            @WebParam(name = "domain", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String domain,
            @WebParam(name = "userName", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String password,
            @WebParam(name = "locale", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String locale);

    /**
     *
     * @param sessionID
     * @return
     *     returns int
     */
    @WebMethod(operationName = "ContinueSession", action = "http://parsec.ru/Parsec3IntergationService/ContinueSession")
    @WebResult(name = "ContinueSessionResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "ContinueSession", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.ContinueSession")
    @ResponseWrapper(localName = "ContinueSessionResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.ContinueSessionResponse")
    public int continueSession(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID);

    /**
     *
     * @param sessionID
     */
    @WebMethod(operationName = "CloseSession", action = "http://parsec.ru/Parsec3IntergationService/CloseSession")
    @RequestWrapper(localName = "CloseSession", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.CloseSession")
    @ResponseWrapper(localName = "CloseSessionResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.CloseSessionResponse")
    public void closeSession(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID);

    /**
     *
     * @param orgUnitID
     * @param sessionID
     * @return
     *     returns ru.parsec.parsec3intergationservice.OrgUnit
     */
    @WebMethod(operationName = "GetOrgUnit", action = "http://parsec.ru/Parsec3IntergationService/GetOrgUnit")
    @WebResult(name = "GetOrgUnitResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetOrgUnit", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetOrgUnit")
    @ResponseWrapper(localName = "GetOrgUnitResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetOrgUnitResponse")
    public OrgUnit getOrgUnit(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "orgUnitID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String orgUnitID);

    /**
     *
     * @param orgUnitID
     * @param sessionID
     * @return
     *     returns ru.parsec.parsec3intergationservice.ArrayOfBaseObject
     */
    @WebMethod(operationName = "GetOrgUnitSubItems", action = "http://parsec.ru/Parsec3IntergationService/GetOrgUnitSubItems")
    @WebResult(name = "GetOrgUnitSubItemsResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetOrgUnitSubItems", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetOrgUnitSubItems")
    @ResponseWrapper(localName = "GetOrgUnitSubItemsResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetOrgUnitSubItemsResponse")
    public ArrayOfBaseObject getOrgUnitSubItems(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "orgUnitID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String orgUnitID);

    /**
     *
     * @param sessionID
     * @return
     *     returns ru.parsec.parsec3intergationservice.ArrayOfOrgUnit
     */
    @WebMethod(operationName = "GetOrgUnitsHierarhy", action = "http://parsec.ru/Parsec3IntergationService/GetOrgUnitsHierarhy")
    @WebResult(name = "GetOrgUnitsHierarhyResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetOrgUnitsHierarhy", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetOrgUnitsHierarhy")
    @ResponseWrapper(localName = "GetOrgUnitsHierarhyResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetOrgUnitsHierarhyResponse")
    public ArrayOfOrgUnit getOrgUnitsHierarhy(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID);

    /**
     *
     * @param sessionID
     * @return
     *     returns ru.parsec.parsec3intergationservice.ArrayOfBaseObject
     */
    @WebMethod(operationName = "GetOrgUnitsHierarhyWithPersons", action = "http://parsec.ru/Parsec3IntergationService/GetOrgUnitsHierarhyWithPersons")
    @WebResult(name = "GetOrgUnitsHierarhyWithPersonsResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetOrgUnitsHierarhyWithPersons", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetOrgUnitsHierarhyWithPersons")
    @ResponseWrapper(localName = "GetOrgUnitsHierarhyWithPersonsResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetOrgUnitsHierarhyWithPersonsResponse")
    public ArrayOfBaseObject getOrgUnitsHierarhyWithPersons(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID);

    /**
     *
     * @param sessionID
     * @return
     *     returns ru.parsec.parsec3intergationservice.ArrayOfBaseObject
     */
    @WebMethod(operationName = "GetOrgUnitsHierarhyWithVisitors", action = "http://parsec.ru/Parsec3IntergationService/GetOrgUnitsHierarhyWithVisitors")
    @WebResult(name = "GetOrgUnitsHierarhyWithVisitorsResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetOrgUnitsHierarhyWithVisitors", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetOrgUnitsHierarhyWithVisitors")
    @ResponseWrapper(localName = "GetOrgUnitsHierarhyWithVisitorsResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetOrgUnitsHierarhyWithVisitorsResponse")
    public ArrayOfBaseObject getOrgUnitsHierarhyWithVisitors(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID);

    /**
     *
     * @param orgUnitID
     * @param sessionID
     * @return
     *     returns ru.parsec.parsec3intergationservice.ArrayOfBaseObject
     */
    @WebMethod(operationName = "GetOrgUnitSubItemsHierarhyWithPersons", action = "http://parsec.ru/Parsec3IntergationService/GetOrgUnitSubItemsHierarhyWithPersons")
    @WebResult(name = "GetOrgUnitSubItemsHierarhyWithPersonsResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetOrgUnitSubItemsHierarhyWithPersons", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetOrgUnitSubItemsHierarhyWithPersons")
    @ResponseWrapper(localName = "GetOrgUnitSubItemsHierarhyWithPersonsResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetOrgUnitSubItemsHierarhyWithPersonsResponse")
    public ArrayOfBaseObject getOrgUnitSubItemsHierarhyWithPersons(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "orgUnitID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String orgUnitID);

    /**
     *
     * @param orgUnitID
     * @param sessionID
     * @return
     *     returns ru.parsec.parsec3intergationservice.ArrayOfBaseObject
     */
    @WebMethod(operationName = "GetOrgUnitSubItemsHierarhyWithVisitors", action = "http://parsec.ru/Parsec3IntergationService/GetOrgUnitSubItemsHierarhyWithVisitors")
    @WebResult(name = "GetOrgUnitSubItemsHierarhyWithVisitorsResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetOrgUnitSubItemsHierarhyWithVisitors", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetOrgUnitSubItemsHierarhyWithVisitors")
    @ResponseWrapper(localName = "GetOrgUnitSubItemsHierarhyWithVisitorsResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetOrgUnitSubItemsHierarhyWithVisitorsResponse")
    public ArrayOfBaseObject getOrgUnitSubItemsHierarhyWithVisitors(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "orgUnitID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String orgUnitID);

    /**
     *
     * @param sessionID
     * @param personID
     * @return
     *     returns ru.parsec.parsec3intergationservice.PersonWithPhoto
     */
    @WebMethod(operationName = "GetPerson", action = "http://parsec.ru/Parsec3IntergationService/GetPerson")
    @WebResult(name = "GetPersonResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetPerson", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetPerson")
    @ResponseWrapper(localName = "GetPersonResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetPersonResponse")
    public PersonWithPhoto getPerson(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "personID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String personID);

    /**
     *
     * @param sessionID
     * @return
     *     returns ru.parsec.parsec3intergationservice.ArrayOfAccessGroup
     */
    @WebMethod(operationName = "GetAccessGroups", action = "http://parsec.ru/Parsec3IntergationService/GetAccessGroups")
    @WebResult(name = "GetAccessGroupsResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetAccessGroups", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetAccessGroups")
    @ResponseWrapper(localName = "GetAccessGroupsResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetAccessGroupsResponse")
    public ArrayOfAccessGroup getAccessGroups(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID);

    /**
     *
     * @param sessionID
     * @param personID
     * @return
     *     returns ru.parsec.parsec3intergationservice.ArrayOfIdentifier
     */
    @WebMethod(operationName = "GetPersonIdentifiers", action = "http://parsec.ru/Parsec3IntergationService/GetPersonIdentifiers")
    @WebResult(name = "GetPersonIdentifiersResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetPersonIdentifiers", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetPersonIdentifiers")
    @ResponseWrapper(localName = "GetPersonIdentifiersResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetPersonIdentifiersResponse")
    public ArrayOfIdentifier getPersonIdentifiers(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "personID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String personID);

    /**
     *
     * @param person
     * @param sessionID
     * @return
     *     returns ru.parsec.parsec3intergationservice.GuidResult
     */
    @WebMethod(operationName = "CreatePerson", action = "http://parsec.ru/Parsec3IntergationService/CreatePerson")
    @WebResult(name = "CreatePersonResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "CreatePerson", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.CreatePerson")
    @ResponseWrapper(localName = "CreatePersonResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.CreatePersonResponse")
    public GuidResult createPerson(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "person", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    Person person);

    /**
     *
     * @param person
     * @param sessionID
     * @return
     *     returns ru.parsec.parsec3intergationservice.GuidResult
     */
    @WebMethod(operationName = "CreateVisitor", action = "http://parsec.ru/Parsec3IntergationService/CreateVisitor")
    @WebResult(name = "CreateVisitorResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "CreateVisitor", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.CreateVisitor")
    @ResponseWrapper(localName = "CreateVisitorResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.CreateVisitorResponse")
    public GuidResult createVisitor(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "person", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    Person person);

    /**
     *
     * @param sessionID
     * @param personID
     * @return
     *     returns ru.parsec.parsec3intergationservice.GuidResult
     */
    @WebMethod(operationName = "OpenPersonEditingSession", action = "http://parsec.ru/Parsec3IntergationService/OpenPersonEditingSession")
    @WebResult(name = "OpenPersonEditingSessionResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "OpenPersonEditingSession", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.OpenPersonEditingSession")
    @ResponseWrapper(localName = "OpenPersonEditingSessionResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.OpenPersonEditingSessionResponse")
    public GuidResult openPersonEditingSession(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "personID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String personID);

    /**
     *
     * @param personEditSessionID
     */
    @WebMethod(operationName = "ClosePersonEditingSession", action = "http://parsec.ru/Parsec3IntergationService/ClosePersonEditingSession")
    @RequestWrapper(localName = "ClosePersonEditingSession", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.ClosePersonEditingSession")
    @ResponseWrapper(localName = "ClosePersonEditingSessionResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.ClosePersonEditingSessionResponse")
    public void closePersonEditingSession(
            @WebParam(name = "personEditSessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String personEditSessionID);

    /**
     *
     * @param personEditSessionID
     * @param person
     * @return
     *     returns ru.parsec.parsec3intergationservice.BaseResult
     */
    @WebMethod(operationName = "SavePerson", action = "http://parsec.ru/Parsec3IntergationService/SavePerson")
    @WebResult(name = "SavePersonResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "SavePerson", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.SavePerson")
    @ResponseWrapper(localName = "SavePersonResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.SavePersonResponse")
    public BaseResult savePerson(
            @WebParam(name = "personEditSessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String personEditSessionID,
            @WebParam(name = "person", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    BasePerson person);

    /**
     *
     * @param personEditSessionID
     * @param photoByteArray
     * @return
     *     returns ru.parsec.parsec3intergationservice.BaseResult
     */
    @WebMethod(operationName = "SetPersonPhoto", action = "http://parsec.ru/Parsec3IntergationService/SetPersonPhoto")
    @WebResult(name = "SetPersonPhotoResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "SetPersonPhoto", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.SetPersonPhoto")
    @ResponseWrapper(localName = "SetPersonPhotoResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.SetPersonPhotoResponse")
    public BaseResult setPersonPhoto(
            @WebParam(name = "personEditSessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String personEditSessionID,
            @WebParam(name = "photoByteArray", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    byte[] photoByteArray);

    /**
     *
     * @param personEditSessionID
     * @param orgUnitID
     * @return
     *     returns ru.parsec.parsec3intergationservice.BaseResult
     */
    @WebMethod(operationName = "SetPersonOrgUnit", action = "http://parsec.ru/Parsec3IntergationService/SetPersonOrgUnit")
    @WebResult(name = "SetPersonOrgUnitResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "SetPersonOrgUnit", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.SetPersonOrgUnit")
    @ResponseWrapper(localName = "SetPersonOrgUnitResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.SetPersonOrgUnitResponse")
    public BaseResult setPersonOrgUnit(
            @WebParam(name = "personEditSessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String personEditSessionID,
            @WebParam(name = "orgUnitID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String orgUnitID);

    /**
     *
     * @param sessionID
     * @param personID
     * @return
     *     returns ru.parsec.parsec3intergationservice.BaseResult
     */
    @WebMethod(operationName = "DeletePerson", action = "http://parsec.ru/Parsec3IntergationService/DeletePerson")
    @WebResult(name = "DeletePersonResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "DeletePerson", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.DeletePerson")
    @ResponseWrapper(localName = "DeletePersonResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.DeletePersonResponse")
    public BaseResult deletePerson(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "personID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String personID);

    /**
     *
     * @param sessionID
     * @param orgUnit
     * @return
     *     returns ru.parsec.parsec3intergationservice.GuidResult
     */
    @WebMethod(operationName = "CreateOrgUnit", action = "http://parsec.ru/Parsec3IntergationService/CreateOrgUnit")
    @WebResult(name = "CreateOrgUnitResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "CreateOrgUnit", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.CreateOrgUnit")
    @ResponseWrapper(localName = "CreateOrgUnitResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.CreateOrgUnitResponse")
    public GuidResult createOrgUnit(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "orgUnit", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    OrgUnit orgUnit);

    /**
     *
     * @param orgUnitID
     * @param sessionID
     * @return
     *     returns ru.parsec.parsec3intergationservice.GuidResult
     */
    @WebMethod(operationName = "OpenOrgUnitEditingSession", action = "http://parsec.ru/Parsec3IntergationService/OpenOrgUnitEditingSession")
    @WebResult(name = "OpenOrgUnitEditingSessionResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "OpenOrgUnitEditingSession", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.OpenOrgUnitEditingSession")
    @ResponseWrapper(localName = "OpenOrgUnitEditingSessionResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.OpenOrgUnitEditingSessionResponse")
    public GuidResult openOrgUnitEditingSession(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "orgUnitID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String orgUnitID);

    /**
     *
     * @param orgUnitEditSessionID
     */
    @WebMethod(operationName = "CloseOrgUnitEditingSession", action = "http://parsec.ru/Parsec3IntergationService/CloseOrgUnitEditingSession")
    @RequestWrapper(localName = "CloseOrgUnitEditingSession", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.CloseOrgUnitEditingSession")
    @ResponseWrapper(localName = "CloseOrgUnitEditingSessionResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.CloseOrgUnitEditingSessionResponse")
    public void closeOrgUnitEditingSession(
            @WebParam(name = "orgUnitEditSessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String orgUnitEditSessionID);

    /**
     *
     * @param orgUnit
     * @param orgUnitEditSessionID
     * @return
     *     returns ru.parsec.parsec3intergationservice.BaseResult
     */
    @WebMethod(operationName = "SaveOrgUnit", action = "http://parsec.ru/Parsec3IntergationService/SaveOrgUnit")
    @WebResult(name = "SaveOrgUnitResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "SaveOrgUnit", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.SaveOrgUnit")
    @ResponseWrapper(localName = "SaveOrgUnitResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.SaveOrgUnitResponse")
    public BaseResult saveOrgUnit(
            @WebParam(name = "orgUnitEditSessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String orgUnitEditSessionID,
            @WebParam(name = "orgUnit", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    BaseOrgUnit orgUnit);

    /**
     *
     * @param orgUnitID
     * @param sessionID
     * @return
     *     returns ru.parsec.parsec3intergationservice.BaseResult
     */
    @WebMethod(operationName = "DeleteOrgUnit", action = "http://parsec.ru/Parsec3IntergationService/DeleteOrgUnit")
    @WebResult(name = "DeleteOrgUnitResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "DeleteOrgUnit", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.DeleteOrgUnit")
    @ResponseWrapper(localName = "DeleteOrgUnitResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.DeleteOrgUnitResponse")
    public BaseResult deleteOrgUnit(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "orgUnitID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String orgUnitID);

    /**
     *
     * @param sessionID
     * @param code
     * @return
     *     returns ru.parsec.parsec3intergationservice.BaseResult
     */
    @WebMethod(operationName = "DeleteIdentifier", action = "http://parsec.ru/Parsec3IntergationService/DeleteIdentifier")
    @WebResult(name = "DeleteIdentifierResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "DeleteIdentifier", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.DeleteIdentifier")
    @ResponseWrapper(localName = "DeleteIdentifierResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.DeleteIdentifierResponse")
    public BaseResult deleteIdentifier(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "Code", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String code);

    /**
     *
     * @param personEditSessionID
     * @param identifier
     * @return
     *     returns ru.parsec.parsec3intergationservice.BaseResult
     */
    @WebMethod(operationName = "AddPersonIdentifier", action = "http://parsec.ru/Parsec3IntergationService/AddPersonIdentifier")
    @WebResult(name = "AddPersonIdentifierResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "AddPersonIdentifier", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.AddPersonIdentifier")
    @ResponseWrapper(localName = "AddPersonIdentifierResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.AddPersonIdentifierResponse")
    public BaseResult addPersonIdentifier(
            @WebParam(name = "personEditSessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String personEditSessionID,
            @WebParam(name = "identifier", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    BaseIdentifier identifier);

    /**
     *
     * @param personEditSessionID
     * @param identifier
     * @return
     *     returns ru.parsec.parsec3intergationservice.BaseResult
     */
    @WebMethod(operationName = "ChangePersonIdentifier", action = "http://parsec.ru/Parsec3IntergationService/ChangePersonIdentifier")
    @WebResult(name = "ChangePersonIdentifierResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "ChangePersonIdentifier", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.ChangePersonIdentifier")
    @ResponseWrapper(localName = "ChangePersonIdentifierResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.ChangePersonIdentifierResponse")
    public BaseResult changePersonIdentifier(
            @WebParam(name = "personEditSessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String personEditSessionID,
            @WebParam(name = "identifier", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    BaseIdentifier identifier);

    /**
     *
     * @param sessionID
     * @return
     *     returns ru.parsec.parsec3intergationservice.ArrayOfTerritory
     */
    @WebMethod(operationName = "GetTerritoriesHierarhy", action = "http://parsec.ru/Parsec3IntergationService/GetTerritoriesHierarhy")
    @WebResult(name = "GetTerritoriesHierarhyResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetTerritoriesHierarhy", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetTerritoriesHierarhy")
    @ResponseWrapper(localName = "GetTerritoriesHierarhyResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetTerritoriesHierarhyResponse")
    public ArrayOfTerritory getTerritoriesHierarhy(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID);

    /**
     *
     * @param sessionID
     * @param terraID
     * @return
     *     returns ru.parsec.parsec3intergationservice.ArrayOfBaseTerritory
     */
    @WebMethod(operationName = "GetTerritorySubItems", action = "http://parsec.ru/Parsec3IntergationService/GetTerritorySubItems")
    @WebResult(name = "GetTerritorySubItemsResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetTerritorySubItems", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetTerritorySubItems")
    @ResponseWrapper(localName = "GetTerritorySubItemsResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetTerritorySubItemsResponse")
    public ArrayOfBaseTerritory getTerritorySubItems(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "TerraID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String terraID);

    /**
     *
     * @param sessionID
     * @param dtTo
     * @param territoryID
     * @param persNodeID
     * @param dtFrom
     * @return
     *     returns ru.parsec.parsec3intergationservice.EventsHistoryResult
     */
    @WebMethod(operationName = "GetEvents", action = "http://parsec.ru/Parsec3IntergationService/GetEvents")
    @WebResult(name = "GetEventsResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetEvents", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetEvents")
    @ResponseWrapper(localName = "GetEventsResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetEventsResponse")
    public EventsHistoryResult getEvents(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "TerritoryID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String territoryID,
            @WebParam(name = "PersNodeID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String persNodeID,
            @WebParam(name = "dtFrom", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    XMLGregorianCalendar dtFrom,
            @WebParam(name = "dtTo", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    XMLGregorianCalendar dtTo);

    /**
     *
     * @param sessionID
     * @return
     *     returns ru.parsec.parsec3intergationservice.ArrayOfPersonExtraFieldTemplate
     */
    @WebMethod(operationName = "GetPersonExtraFieldTemplates", action = "http://parsec.ru/Parsec3IntergationService/GetPersonExtraFieldTemplates")
    @WebResult(name = "GetPersonExtraFieldTemplatesResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetPersonExtraFieldTemplates", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetPersonExtraFieldTemplates")
    @ResponseWrapper(localName = "GetPersonExtraFieldTemplatesResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetPersonExtraFieldTemplatesResponse")
    public ArrayOfPersonExtraFieldTemplate getPersonExtraFieldTemplates(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID);

    /**
     *
     * @param templateID
     * @param sessionID
     * @param personID
     * @return
     *     returns ru.parsec.parsec3intergationservice.ObjectResult
     */
    @WebMethod(operationName = "GetPersonExtraFieldValue", action = "http://parsec.ru/Parsec3IntergationService/GetPersonExtraFieldValue")
    @WebResult(name = "GetPersonExtraFieldValueResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetPersonExtraFieldValue", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetPersonExtraFieldValue")
    @ResponseWrapper(localName = "GetPersonExtraFieldValueResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetPersonExtraFieldValueResponse")
    public ObjectResult getPersonExtraFieldValue(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "personID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String personID,
            @WebParam(name = "templateID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String templateID);

    /**
     *
     * @param templateID
     * @param sessionID
     * @param personID
     * @return
     *     returns ru.parsec.parsec3intergationservice.StringResult
     */
    @WebMethod(operationName = "GetPersonExtraFieldValueString", action = "http://parsec.ru/Parsec3IntergationService/GetPersonExtraFieldValueString")
    @WebResult(name = "GetPersonExtraFieldValueStringResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetPersonExtraFieldValueString", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetPersonExtraFieldValueString")
    @ResponseWrapper(localName = "GetPersonExtraFieldValueStringResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetPersonExtraFieldValueStringResponse")
    public StringResult getPersonExtraFieldValueString(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "personID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String personID,
            @WebParam(name = "templateID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String templateID);

    /**
     *
     * @param personEditSessionID
     * @param templateID
     * @param value
     * @return
     *     returns ru.parsec.parsec3intergationservice.BaseResult
     */
    @WebMethod(operationName = "SetPersonExtraFieldValue", action = "http://parsec.ru/Parsec3IntergationService/SetPersonExtraFieldValue")
    @WebResult(name = "SetPersonExtraFieldValueResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "SetPersonExtraFieldValue", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.SetPersonExtraFieldValue")
    @ResponseWrapper(localName = "SetPersonExtraFieldValueResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.SetPersonExtraFieldValueResponse")
    public BaseResult setPersonExtraFieldValue(
            @WebParam(name = "personEditSessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String personEditSessionID,
            @WebParam(name = "templateID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String templateID,
            @WebParam(name = "value", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    Object value);

    /**
     *
     * @param sessionID
     * @param personID
     * @return
     *     returns ru.parsec.parsec3intergationservice.ArrayOfExtraFieldValue
     */
    @WebMethod(operationName = "GetPersonExtraFieldValues", action = "http://parsec.ru/Parsec3IntergationService/GetPersonExtraFieldValues")
    @WebResult(name = "GetPersonExtraFieldValuesResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetPersonExtraFieldValues", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetPersonExtraFieldValues")
    @ResponseWrapper(localName = "GetPersonExtraFieldValuesResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetPersonExtraFieldValuesResponse")
    public ArrayOfExtraFieldValue getPersonExtraFieldValues(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "personID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String personID);

    /**
     *
     * @param personEditSessionID
     * @param values
     * @return
     *     returns ru.parsec.parsec3intergationservice.BaseResult
     */
    @WebMethod(operationName = "SetPersonExtraFieldValues", action = "http://parsec.ru/Parsec3IntergationService/SetPersonExtraFieldValues")
    @WebResult(name = "SetPersonExtraFieldValuesResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "SetPersonExtraFieldValues", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.SetPersonExtraFieldValues")
    @ResponseWrapper(localName = "SetPersonExtraFieldValuesResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.SetPersonExtraFieldValuesResponse")
    public BaseResult setPersonExtraFieldValues(
            @WebParam(name = "personEditSessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String personEditSessionID,
            @WebParam(name = "values", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    ArrayOfExtraFieldValue values);

    /**
     *
     * @param sessionID
     * @param value
     * @return
     *     returns ru.parsec.parsec3intergationservice.BaseResult
     */
    @WebMethod(operationName = "ValidateExtraFieldValue", action = "http://parsec.ru/Parsec3IntergationService/ValidateExtraFieldValue")
    @WebResult(name = "ValidateExtraFieldValueResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "ValidateExtraFieldValue", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.ValidateExtraFieldValue")
    @ResponseWrapper(localName = "ValidateExtraFieldValueResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.ValidateExtraFieldValueResponse")
    public BaseResult validateExtraFieldValue(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "value", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    ExtraFieldValue value);

    /**
     *
     * @param sessionID
     * @param requestNumber
     * @return
     *     returns ru.parsec.parsec3intergationservice.VisitorRequest
     */
    @WebMethod(operationName = "FindVisitorRequest", action = "http://parsec.ru/Parsec3IntergationService/FindVisitorRequest")
    @WebResult(name = "FindVisitorRequestResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "FindVisitorRequest", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.FindVisitorRequest")
    @ResponseWrapper(localName = "FindVisitorRequestResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.FindVisitorRequestResponse")
    public VisitorRequest findVisitorRequest(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "requestNumber", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    int requestNumber);

    /**
     *
     * @param sessionID
     * @return
     *     returns ru.parsec.parsec3intergationservice.ArrayOfVisitorRequest
     */
    @WebMethod(operationName = "GetAcceptedVisitorRequests", action = "http://parsec.ru/Parsec3IntergationService/GetAcceptedVisitorRequests")
    @WebResult(name = "GetAcceptedVisitorRequestsResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetAcceptedVisitorRequests", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetAcceptedVisitorRequests")
    @ResponseWrapper(localName = "GetAcceptedVisitorRequestsResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetAcceptedVisitorRequestsResponse")
    public ArrayOfVisitorRequest getAcceptedVisitorRequests(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID);

    /**
     *
     * @param sessionID
     * @param requestID
     * @param cardCode
     * @return
     *     returns ru.parsec.parsec3intergationservice.BaseResult
     */
    @WebMethod(operationName = "ActivateVisitorRequest", action = "http://parsec.ru/Parsec3IntergationService/ActivateVisitorRequest")
    @WebResult(name = "ActivateVisitorRequestResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "ActivateVisitorRequest", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.ActivateVisitorRequest")
    @ResponseWrapper(localName = "ActivateVisitorRequestResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.ActivateVisitorRequestResponse")
    public BaseResult activateVisitorRequest(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "requestID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String requestID,
            @WebParam(name = "cardCode", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String cardCode);

    /**
     *
     * @param middlename
     * @param sessionID
     * @param lastname
     * @param firstname
     * @return
     *     returns ru.parsec.parsec3intergationservice.ArrayOfPerson
     */
    @WebMethod(operationName = "FindPeople", action = "http://parsec.ru/Parsec3IntergationService/FindPeople")
    @WebResult(name = "FindPeopleResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "FindPeople", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.FindPeople")
    @ResponseWrapper(localName = "FindPeopleResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.FindPeopleResponse")
    public ArrayOfPerson findPeople(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "lastname", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String lastname,
            @WebParam(name = "firstname", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String firstname,
            @WebParam(name = "middlename", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String middlename);

    /**
     *
     * @param middlename
     * @param sessionID
     * @param lastname
     * @param firstname
     * @return
     *     returns ru.parsec.parsec3intergationservice.ArrayOfPerson
     */
    @WebMethod(operationName = "FindVisitors", action = "http://parsec.ru/Parsec3IntergationService/FindVisitors")
    @WebResult(name = "FindVisitorsResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "FindVisitors", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.FindVisitors")
    @ResponseWrapper(localName = "FindVisitorsResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.FindVisitorsResponse")
    public ArrayOfPerson findVisitors(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "lastname", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String lastname,
            @WebParam(name = "firstname", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String firstname,
            @WebParam(name = "middlename", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String middlename);

    /**
     *
     * @param sessionID
     * @return
     *     returns ru.parsec.parsec3intergationservice.ArrayOfSchedule
     */
    @WebMethod(operationName = "GetAccessSchedules", action = "http://parsec.ru/Parsec3IntergationService/GetAccessSchedules")
    @WebResult(name = "GetAccessSchedulesResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetAccessSchedules", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetAccessSchedules")
    @ResponseWrapper(localName = "GetAccessSchedulesResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetAccessSchedulesResponse")
    public ArrayOfSchedule getAccessSchedules(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID);

    /**
     *
     * @param to
     * @param sessionID
     * @param from
     * @param scheduleID
     * @return
     *     returns ru.parsec.parsec3intergationservice.ArrayOfTimeInterval
     */
    @WebMethod(operationName = "GetScheduleIntervals", action = "http://parsec.ru/Parsec3IntergationService/GetScheduleIntervals")
    @WebResult(name = "GetScheduleIntervalsResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetScheduleIntervals", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetScheduleIntervals")
    @ResponseWrapper(localName = "GetScheduleIntervalsResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetScheduleIntervalsResponse")
    public ArrayOfTimeInterval getScheduleIntervals(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "scheduleID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String scheduleID,
            @WebParam(name = "from", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    XMLGregorianCalendar from,
            @WebParam(name = "to", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    XMLGregorianCalendar to);

    /**
     *
     * @param sessionID
     * @param territories
     * @param scheduleID
     * @return
     *     returns ru.parsec.parsec3intergationservice.GuidResult
     */
    @WebMethod(operationName = "CreateTempAccessGroup", action = "http://parsec.ru/Parsec3IntergationService/CreateTempAccessGroup")
    @WebResult(name = "CreateTempAccessGroupResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "CreateTempAccessGroup", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.CreateTempAccessGroup")
    @ResponseWrapper(localName = "CreateTempAccessGroupResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.CreateTempAccessGroupResponse")
    public GuidResult createTempAccessGroup(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "scheduleID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String scheduleID,
            @WebParam(name = "territories", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    ArrayOfGuid territories);

    /**
     *
     * @param sessionID
     * @return
     *     returns ru.parsec.parsec3intergationservice.Territory
     */
    @WebMethod(operationName = "GetRootTerritory", action = "http://parsec.ru/Parsec3IntergationService/GetRootTerritory")
    @WebResult(name = "GetRootTerritoryResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetRootTerritory", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetRootTerritory")
    @ResponseWrapper(localName = "GetRootTerritoryResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetRootTerritoryResponse")
    public Territory getRootTerritory(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID);

    /**
     *
     * @param sessionID
     * @param territoryID
     * @return
     *     returns ru.parsec.parsec3intergationservice.Territory
     */
    @WebMethod(operationName = "GetTerritory", action = "http://parsec.ru/Parsec3IntergationService/GetTerritory")
    @WebResult(name = "GetTerritoryResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetTerritory", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetTerritory")
    @ResponseWrapper(localName = "GetTerritoryResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetTerritoryResponse")
    public Territory getTerritory(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "territoryID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String territoryID);

    /**
     *
     * @param sessionID
     * @return
     *     returns ru.parsec.parsec3intergationservice.OrgUnit
     */
    @WebMethod(operationName = "GetRootOrgUnit", action = "http://parsec.ru/Parsec3IntergationService/GetRootOrgUnit")
    @WebResult(name = "GetRootOrgUnitResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetRootOrgUnit", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetRootOrgUnit")
    @ResponseWrapper(localName = "GetRootOrgUnitResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetRootOrgUnitResponse")
    public OrgUnit getRootOrgUnit(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID);

    /**
     *
     * @return
     *     returns ru.parsec.parsec3intergationservice.ArrayOfDomain
     */
    @WebMethod(operationName = "GetDomains", action = "http://parsec.ru/Parsec3IntergationService/GetDomains")
    @WebResult(name = "GetDomainsResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetDomains", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetDomains")
    @ResponseWrapper(localName = "GetDomainsResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetDomainsResponse")
    public ArrayOfDomain getDomains();

    /**
     *
     * @param sessionID
     * @param request
     * @return
     *     returns ru.parsec.parsec3intergationservice.VisitorRequest
     */
    @WebMethod(operationName = "CreateVisitorRequest", action = "http://parsec.ru/Parsec3IntergationService/CreateVisitorRequest")
    @WebResult(name = "CreateVisitorRequestResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "CreateVisitorRequest", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.CreateVisitorRequest")
    @ResponseWrapper(localName = "CreateVisitorRequestResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.CreateVisitorRequestResponse")
    public VisitorRequest createVisitorRequest(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "request", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    VisitorRequest request);

    /**
     *
     * @param sessionID
     * @param requestID
     * @return
     *     returns ru.parsec.parsec3intergationservice.BaseResult
     */
    @WebMethod(operationName = "DeleteIssuedVisitorRequest", action = "http://parsec.ru/Parsec3IntergationService/DeleteIssuedVisitorRequest")
    @WebResult(name = "DeleteIssuedVisitorRequestResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "DeleteIssuedVisitorRequest", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.DeleteIssuedVisitorRequest")
    @ResponseWrapper(localName = "DeleteIssuedVisitorRequestResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.DeleteIssuedVisitorRequestResponse")
    public BaseResult deleteIssuedVisitorRequest(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "requestID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String requestID);

    /**
     *
     * @param sessionID
     * @return
     *     returns ru.parsec.parsec3intergationservice.ArrayOfVisitorRequest
     */
    @WebMethod(operationName = "GetIssuedVisitorRequests", action = "http://parsec.ru/Parsec3IntergationService/GetIssuedVisitorRequests")
    @WebResult(name = "GetIssuedVisitorRequestsResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetIssuedVisitorRequests", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetIssuedVisitorRequests")
    @ResponseWrapper(localName = "GetIssuedVisitorRequestsResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetIssuedVisitorRequestsResponse")
    public ArrayOfVisitorRequest getIssuedVisitorRequests(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID);

    /**
     *
     * @param sessionID
     * @param requestID
     * @return
     *     returns ru.parsec.parsec3intergationservice.VisitorRequest
     */
    @WebMethod(operationName = "GetVisitorRequest", action = "http://parsec.ru/Parsec3IntergationService/GetVisitorRequest")
    @WebResult(name = "GetVisitorRequestResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetVisitorRequest", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetVisitorRequest")
    @ResponseWrapper(localName = "GetVisitorRequestResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetVisitorRequestResponse")
    public VisitorRequest getVisitorRequest(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "requestID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String requestID);

    /**
     *
     * @param sessionID
     * @param request
     * @return
     *     returns ru.parsec.parsec3intergationservice.BaseResult
     */
    @WebMethod(operationName = "SaveVisitorRequest", action = "http://parsec.ru/Parsec3IntergationService/SaveVisitorRequest")
    @WebResult(name = "SaveVisitorRequestResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "SaveVisitorRequest", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.SaveVisitorRequest")
    @ResponseWrapper(localName = "SaveVisitorRequestResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.SaveVisitorRequestResponse")
    public BaseResult saveVisitorRequest(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "request", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    VisitorRequest request);

    /**
     *
     * @param sessionID
     * @param parameters
     * @return
     *     returns ru.parsec.parsec3intergationservice.GuidResult
     */
    @WebMethod(operationName = "OpenEventHistorySession", action = "http://parsec.ru/Parsec3IntergationService/OpenEventHistorySession")
    @WebResult(name = "OpenEventHistorySessionResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "OpenEventHistorySession", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.OpenEventHistorySession")
    @ResponseWrapper(localName = "OpenEventHistorySessionResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.OpenEventHistorySessionResponse")
    public GuidResult openEventHistorySession(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "parameters", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    EventHistoryQueryParams parameters);

    /**
     *
     * @param sessionID
     * @param eventHistorySessionID
     */
    @WebMethod(operationName = "CloseEventHistorySession", action = "http://parsec.ru/Parsec3IntergationService/CloseEventHistorySession")
    @RequestWrapper(localName = "CloseEventHistorySession", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.CloseEventHistorySession")
    @ResponseWrapper(localName = "CloseEventHistorySessionResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.CloseEventHistorySessionResponse")
    public void closeEventHistorySession(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "eventHistorySessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String eventHistorySessionID);

    /**
     *
     * @param sessionID
     * @param eventHistorySessionID
     * @return
     *     returns int
     */
    @WebMethod(operationName = "GetEventHistoryResultCount", action = "http://parsec.ru/Parsec3IntergationService/GetEventHistoryResultCount")
    @WebResult(name = "GetEventHistoryResultCountResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetEventHistoryResultCount", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetEventHistoryResultCount")
    @ResponseWrapper(localName = "GetEventHistoryResultCountResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetEventHistoryResultCountResponse")
    public int getEventHistoryResultCount(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "eventHistorySessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String eventHistorySessionID);

    /**
     *
     * @param sessionID
     * @param count
     * @param eventHistorySessionID
     * @param offset
     * @param fields
     * @return
     *     returns ru.parsec.parsec3intergationservice.ArrayOfEventObject
     */
    @WebMethod(operationName = "GetEventHistoryResult", action = "http://parsec.ru/Parsec3IntergationService/GetEventHistoryResult")
    @WebResult(name = "GetEventHistoryResultResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "GetEventHistoryResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetEventHistoryResult")
    @ResponseWrapper(localName = "GetEventHistoryResultResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.GetEventHistoryResultResponse")
    public ArrayOfEventObject getEventHistoryResult(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "eventHistorySessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String eventHistorySessionID,
            @WebParam(name = "fields", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    ArrayOfGuid fields,
            @WebParam(name = "offset", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    int offset,
            @WebParam(name = "count", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    int count);

    /**
     *
     * @param sessionID
     * @param cardCode
     * @return
     *     returns ru.parsec.parsec3intergationservice.Person
     */
    @WebMethod(operationName = "FindPersonByIdentifier", action = "http://parsec.ru/Parsec3IntergationService/FindPersonByIdentifier")
    @WebResult(name = "FindPersonByIdentifierResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "FindPersonByIdentifier", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.FindPersonByIdentifier")
    @ResponseWrapper(localName = "FindPersonByIdentifierResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.FindPersonByIdentifierResponse")
    public Person findPersonByIdentifier(
            @WebParam(name = "sessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String sessionID,
            @WebParam(name = "cardCode", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String cardCode);

    /**
     *
     * @param personEditSessionID
     * @param typeBlock
     * @return
     *     returns ru.parsec.parsec3intergationservice.BaseResult
     */
    @WebMethod(operationName = "BlockPerson", action = "http://parsec.ru/Parsec3IntergationService/BlockPerson")
    @WebResult(name = "BlockPersonResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "BlockPerson", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.BlockPerson")
    @ResponseWrapper(localName = "BlockPersonResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.BlockPersonResponse")
    public BaseResult blockPerson(
            @WebParam(name = "personEditSessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String personEditSessionID,
            @WebParam(name = "typeBlock", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    int typeBlock);

    /**
     *
     * @param personEditSessionID
     * @return
     *     returns ru.parsec.parsec3intergationservice.BaseResult
     */
    @WebMethod(operationName = "UnblockPerson", action = "http://parsec.ru/Parsec3IntergationService/UnblockPerson")
    @WebResult(name = "UnblockPersonResult", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
    @RequestWrapper(localName = "UnblockPerson", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.UnblockPerson")
    @ResponseWrapper(localName = "UnblockPersonResponse", targetNamespace = "http://parsec.ru/Parsec3IntergationService", className = "ru.parsec.parsec3intergationservice.UnblockPersonResponse")
    public BaseResult unblockPerson(
            @WebParam(name = "personEditSessionID", targetNamespace = "http://parsec.ru/Parsec3IntergationService")
                    String personEditSessionID);

}
